### ISSUE TITLE
Documentação

### ISSUE THREAD

**Issue by EsioFreitas** [Escola-em-Casa/resources-escola-em-casa#1]
Olá! @guilacerda  e @joaaogui , estou com umas ideias e dúvidas. 

**Duvidas:**
* Poderíamos usar esse repositório para as documentações? 
* Já tem ideia de quais documentações entregarão valor para o projeto? 

**Ideias:** 
* Acredito que essas documentações entregam valor para o projeto: 
    * Visão
    * Descrição arquitetural
    * Contexto
    * Rich pictures 
    * Guia de estilo
    * Teste de usabilidade

**Comment by guilacerda** [comment]
@EsioFreitas eu acredito que as documentações de cada projeto devam estar em seus respectivos repositórios dentro da pasta docs/ (seguindo um padrão adotado por uma boa parte da comunidade, quando é um produto não framework, ou algo do tipo): https://github.com/DivanteLtd/vue-storefront.

Hoje, as documentações que vejo como relevantes e entregam valor direto ao produto são: Arquitetura, guia de contribuição, guia de estilo e um README muito bem estruturado.

Você poderia me explicar melhor o porque dessas documentações no campo da Ideias entregam valor ao projeto?

**Comment by EsioFreitas** [comment]
@guilacerda , podemos seguir esse padrão sim, mas a duvida que fica: qual vai ser o repositório que vai ficar com a documentação? Visto que temos 4. É importante frisar a importância de todos estiverem juntos também. 

Respondendo a pergunta dos documentos:
* Visão
É um ótimo documento para quem quer conhecer o projeto ou contribuir. Ele vai vai contar sobre a ideia de uma forma mais formal e profissional. 

* Descrição arquitetural
Uma versão mais simples do documento de arquitetura. Acredito que não precise de diagrama de classes, sequencias e entre outros.

* Rich pictures
É uma forma simples de mostrar a ideia. Seria interessante para o publico não técnico e para vender a ideia.

* Teste de usabilidade
Importante para evolução da aplicação. Além disso, é uma forma de cuidarmos dos requisitos não funcionais.

**Comment by joaaogui** [comment]
Olá @EsioFreitas, concordo com o @guilacerda em relação a disposição da documentação. Na minha opinião devem ficar no repositório que a documentação se refere. 

Por exemplo, 

O documento de Descrição arquitetural se refere ao aplicativo android ? Logo, deve ficar no repositório android-escola-em-casa.
O documento de Descrição arquiteturalse refere ao aplicativo ios? Logo, deve ficar no repositório ios-escola-em-casa.

**Comment by joaaogui** [comment]
Não vejo por que documentos relacionados a diferentes repositórios devam ficar juntos. Me parece mais um empecilho para a manuntenção.

**Comment by EsioFreitas** [comment]
@joaaogui , dependendo do documento, ele pode ficar pequeno (até demais), faltando partes ou até mesmo perder o sentido. Vamos usar o exemplo que vc trouxe: quando falamos de um documento de descrição arquitetural, não falamos do aplicativo android ou ios, mas sim de toda aplicação. A maioria dos documentos em si não vai se tratar de um serviço, mas da aplicação. O que mais faz sentido indo nessa lógica seriam criar diagramas, mas também não se seria um bom caminho.

Sobre ser um empecilho para manutenção, não concordo. É muito importante centralizar a informação. Ainda mais em um projeto desses que pode escalar. É importante ter uma visão de produto na hora de documentar, não apenas de código.

**Comment by joaaogui** [comment]
@EsioFreitas Não sei se você já chegou a dar um olhada nos repositórios, mas o aplicativo ios e o aplicativo android são duas aplicações diferentes, em diferentes linguagens, definições e arquiteturas. Não faz sentido definir a arquitetura de um aplicativo android no mesmo documento de um aplicativo ios. 

Porém, reitero, em caso de discordancia, ou se achar que pode entregar algo melhor, crie o PR, o time analisará e agregará ao código, caso concorde.

Valeu!

**Comment by EsioFreitas** [comment]
@joaaogui , o documento é da aplicação, não do serviço. Enfim, vou fazer o que o @guilacerda, já solicitou, criar o PR, e esperar o time analisar e agregar ao código, caso concorde. 

Valeu.

**Comment by joaaogui** [comment]
Boa!
